DROP TABLE IF EXISTS sys_user;

CREATE TABLE sys_user
(
  id      BIGINT NOT NULL COMMENT '主键ID',
  name    VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
  age     INT NULL DEFAULT NULL COMMENT '年龄',
  email   VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
  version INT NULL DEFAULT 1 COMMENT '乐观锁版本',
  deleted INT NULL DEFAULT 1 COMMENT '逻辑删除字段',
  create_time TIMESTAMP NULL,
  PRIMARY KEY (id)
);