DROP TABLE IF EXISTS sys_user;

CREATE TABLE sys_user
(
	id BIGINT NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT NULL DEFAULT NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	wallets VARCHAR(3000) NULL DEFAULT NULL COMMENT '钱包',
	other_info VARCHAR(3000) NULL DEFAULT NULL COMMENT '其他信息',
	PRIMARY KEY (id)
);
