DROP TABLE IF EXISTS user;

CREATE TABLE user
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT(11) NULL DEFAULT NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	PRIMARY KEY (id)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_USER START WITH 10086 INCREMENT BY 1;


DROP TABLE IF EXISTS district;

CREATE TABLE district
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '行政区域名简称',
	city VARCHAR(30) NULL DEFAULT NULL COMMENT '城市',
	district VARCHAR(50) NULL DEFAULT NULL COMMENT '行政区域区',
	PRIMARY KEY (id)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_DISTRICT START WITH 10086 INCREMENT BY 1;


DROP TABLE IF EXISTS city;

CREATE TABLE city
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '城市名称',
	province VARCHAR(50) NULL DEFAULT NULL COMMENT '省份',
	PRIMARY KEY (id)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_CITY START WITH 10086 INCREMENT BY 1;
