DROP TABLE IF EXISTS user;

CREATE TABLE user
(
	id 				BIGINT(20) NOT NULL 			COMMENT '主键ID',
	company_id 		BIGINT(20) NOT NULL 			COMMENT '公司ID',
	name 			VARCHAR(30) NULL DEFAULT NULL 	COMMENT '姓名',
	age 			INT(11) NULL DEFAULT NULL 		COMMENT '年龄',
	email 			VARCHAR(50) NULL DEFAULT NULL 	COMMENT '邮箱',
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS company;

CREATE TABLE company
(
	id 				BIGINT(20) NOT NULL 			COMMENT '主键ID',
	name 			VARCHAR(30) NULL DEFAULT NULL 	COMMENT '公司名称',
	PRIMARY KEY (id)
);