DROP TABLE IF EXISTS sys_user;

CREATE TABLE sys_user
(
	id BIGINT NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT NULL DEFAULT NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
    create_user_id BIGINT NULL DEFAULT NULL COMMENT '创建人ID',
    create_time TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
    update_user_id BIGINT NULL DEFAULT NULL COMMENT '更新人ID',
    update_time TIMESTAMP NULL DEFAULT NULL COMMENT '更新时间',
	PRIMARY KEY (id)
);

